<?php


/**
 * [BEGIN_COT_EXT]
 * Code=githubhelper
 * Name=Get Github Info
 * Category=misc-ext
 * Description=Get Github issues, pull requests, download link
 * Version=1.0.0
 * Date=2015-05-12
 * Author=esclkm
 * Auth_guests=R
 * Lock_guests=12345A
 * Auth_members=RW
 * [END_COT_EXT]
 * 
 *  */
// https://github.com/settings/applications/new
/**
 * [BEGIN_COT_EXT_CONFIG]
 * client_id=01:string:::Client ID
 * client_secret=02:string:::Client Secret
 * [END_COT_EXT_CONFIG]
 */
/**
 * plugin Get Github Info for Cotonti Siena
 * 
 * @package githubhelper
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL');

?>