<?php
/**
 * plugin Get Github Info for Cotonti Siena
 * 
 * @package githubhelper
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL');

$L['cfg_client_id'] = 'Client ID';
$L['cfg_client_id_hint'] = 'Для увеличения количества запросов в час с 60 до 5000, пожалуйста, зарегистрируйте ваше приложение https://github.com/settings/applications/new .';
$L['cfg_client_secret'] = 'Client Secret';


$L['github_page_add'] = 'Быстрое создание страниц при помощи репозитория Github';
$L['repo_href'] = 'Ссылка на репозиторий Github';
$L['repo_nogithublink'] = 'Не указана Ссылка на репозиторий Github';
$L['repo_githublinkincorrect'] = 'Не возможно получить информацию о реппозитории. Возможно ссылка указана неверно';