<?php
/**
 * plugin Get Github Info for Cotonti Siena
 * 
 * @package githubhelper
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL');

$L['cfg_client_id'] = 'Client ID';
$L['cfg_client_id_hint'] = 'All developers need to register (https://github.com/settings/applications/new) their application before getting started. '
	. 'If your OAuth application needs to make unauthenticated calls with a higher rate limit, you can pass your app’s client ID and secret as part of the query string, after registering your application (https://github.com/settings/applications/new).';
$L['cfg_client_secret'] = 'Client Secret';

$L['github_page_add'] = 'Быстрое создание страниц при помощи репозитория Github';
$L['repo_href'] = 'Ссылка на репозиторий Github';
$L['repo_nogithublink'] = 'Не указана Ссылка на репозиторий Github';
$L['repo_githublinkincorrect'] = 'Не возможно получить информацию о реппозитории. Возможно ссылка указана неверно';